---
- name: Deploy Node.js Application
  hosts: webservers
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Node.js application repository
      become_user: "{{ ansible_user }}"
      git:
        repo: https://github.com/krishnavamshi933/node-hello.git
        dest: /home/ubuntu/node-hello  # Change this to the desired path
        version: main  # Specify the branch or tag

    - name: Install PM2 globally
      become: true
      npm:
        name: pm2
        global: yes

    - name: Install application dependencies
      become_user: "{{ ansible_user }}"
      shell: cd /home/ubuntu/node-hello && npm install

    - name: Build the application
      become_user: "{{ ansible_user }}"
      shell: cd /home/ubuntu/node-hello && npm run build 

    - name: Restart or start pm2 process
      become_user: "{{ ansible_user }}"
      shell: cd /home/ubuntu/node-hello && pm2 restart app.js || pm2 start app.js  # Restart or start the pm2 process
