---
- name: Deploy Node.js Application
  hosts: webservers
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install PM2
      become_user: "{{ ansible_user }}"
      npm:
        name: pm2
        path: /home/ubuntu/node-hello
        global: yes

    - name: Clone Node.js application repository
      become_user: "{{ ansible_user }}"
      git:
        repo: https://github.com/krishnavamshi933/node-hello.git
        dest: /home/ubuntu/node-hello  # Change this to the desired path
        version: main  # Specify the branch or tag

    - name: Install application dependencies
      become_user: "{{ ansible_user }}"
      shell:
        cmd: npm install
        chdir: /home/ubuntu/node-hello

    - name: Build the application
      become_user: "{{ ansible_user }}"
      shell:
        cmd: npm run build
        chdir: /home/ubuntu/node-hello

    - name: Restart or start pm2 process
      become_user: "{{ ansible_user }}"
      shell:
        cmd: pm2 restart app.js || pm2 start app.js
        chdir: /home/ubuntu/node-hello
