---
- name: Install Nginx and Create a File
  hosts: "{{ server_ip }}"
  become: true
  gather_facts: true

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      become: true

    - name: Create a sample file
      copy:
        content: "Hello, this file is created by Ansible.\n"
        dest: "/var/www/html/sample.txt"
      become: true
