name: Conditional Workflow

on:
  push:
    branches:
      - main

jobs:
  create-file:

    runs-on: ubuntu-latest

    env:
      FILE_CONTENT: "Default Content"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Connect to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
        port: 22
        script: |
          echo "Connected to the server"
          echo "${FILE_CONTENT}" > /home/ec2-user/example.txt
