name: Conditional Workflow

on:
  push:
    branches:
      - main

jobs:
  create-file:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Connect to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
        port: 22
        script: |
         a="Connected to the server"
          echo "$a" > /home/ec2-user/example1.txt
          rm -rf node-hello
          git clone https://github.com/krishnavamshi933/node-hello
          cd node-hello && node app.js
          
