name: Create Text File on Server

on:
  push:
    branches:
      - main


on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 

jobs:
  create-file:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Connect to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
        port: 22
        script: |
          echo "Connected to the server"
          echo "Hello from GitHub Actions" > /home/ec2-user/example.txt
