name: Node.js CI with Java and Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Deploy to EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
        port: 22
        script: |
          scp -i ${{ secrets.EC2_INSTANCE_PEM_FILE }} -r ./* ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/home/ec2-user
          #ssh -i ${{ secrets.EC2_INSTANCE_PEM_FILE }} ec2-user@${{ secrets.EC2_INSTANCE_IP }} "cd /home/ec2-user && sudo yum install -y java-1.8.0-openjdk-devel && npm install && pm2 restart app.js"
