name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      server-ip:
        description: 'Server IP Address'
        required: true
      username:
        description: 'Server Username'
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ github.event.inputs.server-ip }}
        username: ${{ github.event.inputs.username }}
        key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
        port: 22
        script: |
          git clone https://github.com/krishnavamshi933/node-hello.git && cd node-hello
          npm install           
          npm run build          
          pm2 restart app.js
