name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      server-ip:
        description: 'Server IP Address'
        required: true
      username:
        description: 'Server Username'
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          git pull origin main  
          npm install           
          npm run build          
          pm2 restart app.js
