---
- name: Deploy Node.js Application
  hosts: all
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Node.js application repository
      git:
        repo: https://github.com/krishnavamshi933/node-hello.git
        dest: /path/to/node-hello  # Change this to the desired path
        version: main  # Specify the branch or tag

    - name: Change to the application directory
      become_user: "{{ ansible_user }}"
      shell: /home/ubuntu/node-hello

    - name: Install application dependencies
      become_user: "{{ ansible_user }}"
      shell: npm install

    - name: Build the application
      become_user: "{{ ansible_user }}"
      shell: npm run build

    - name: Restart or start pm2 process
      become_user: "{{ ansible_user }}"
      shell: pm2 restart app.js || pm2 start app.js
