name: Test Connection

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Enter Server IP"
        required: true

jobs:
  test_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Connection
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1
        with:
          playbook: test_connection.yml  # Your test connection playbook
          options: "--inventory ${ { github.event.inputs.server_ip } },"  # Dynamic inventory based on the input
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
